server:
  port: 8080
eureka:
  client:
    service-url:
       defaultZone: http://admin:123456@127.0.0.1:8082/eureka/
spring:
  application:
    name: user-consumer
  datasource:
      username: root
      password: 123456
      url: jdbc:mysql://localhost:3306/test?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowMultiQueries=true
      driver-class-name: com.mysql.jdbc.Driver
