server:
  port: 8080
eureka:
  client:
    service-url:
       defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@127.0.0.1:8082/eureka/
spring:
  application:
    name: user-consumer
  security:
        user:
          name: admin
          password: 123456
