server:
  port: 8081

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/test?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat,wall,log4j
    maxActive: 20 #最大连接数
    initialSize: 5 #初始化数量
    maxWait: 6000
    minIdle: 5
  application:
    name: user-provider
  security:
       user:
         name: admin
         password: 123456
  servlet:
    multipart:
      max-file-size: 10MB

#配置mybatis
mybatis:
    mapper-locations: classpath:mapper/*.xml
    #实体类扫描地址
    type-aliases-package: com.eastday.demo.user;com.eastday.demo.news
    #控制台打印sql
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#通用mapper
mapper:
    mappers:
      - tk.mybatis.mapper.common.Mapper
      - tk.mybatis.mapper.common.MySqlMapper
    not-empty: true
    identity: MYSQL

logging:
    level:
      #显示SQL
      mapper: debug
      #打印日志
      com.eastday.demo: debug

eureka:
  client:
    service-url:
       defaultZone: http://admin:123456@127.0.0.1:8082/eureka/

