server:
  port: 8081

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/test?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowMultiQueries=true
    type: com.alibaba.druid.pool.DruidDataSource #数据源配置
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat,wall,log4j
    maxActive: 20 #最大连接数
    initialSize: 5 #初始化数量
    maxWait: 6000
    minIdle: 5
  application:
    name: user-provider

#配置mybatis
mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.dfw.demo.entity
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8082/eureka

